# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
#
# Examples:
#
# rubocop --format offenses
# rubocop --only Lint/UselessAssignment
# rubocop --only Lint/UselessAssignment -x
AllCops:
  Exclude:
  - bin/**/*
  - config/**/*
  - db/**/*
Metrics/AbcSize:
  Severity: warning
Metrics/BlockLength:
  Exclude:
  - spec/**/*
